version: "3.8"

services:

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306"
    networks:
      - db-net
    volumes:
      - db-admin:/data
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    networks:
      - db-net
    ports:
      - "80:80"
    environment:
      PMA_HOST: mariadb
    depends_on:
      - mariadb

networks:
  db-net:
volumes:
  db-admin: